= How Antora Can Help You and Your Team

== Agile and secure

*Automate the assembly of your secure, nimble static site as changes happen instead of wrestling with a CMS giant.*

Rebuild and deploy your site automatically in a matter of seconds in response to any change. Never have to worry about patching security holes in your deployed CMS application since you don’t have one. All pages are static—​in the JAMstack style. Need to migrate your site to a different domain? Just rebuild the site and relaunch it on the new host.

*Adapt your site to fit seamlessly with your other web properties.*

No site is an island. Sites must play nice with others to maintain a consistent brand and user experiences. Static sites generated by Antora are well-suited for this role. With page templates and a little help from an automated process, you can blend your documentation pages into existing sites, giving the impression it’s all part of a single uniform site.

== Tap into a ready-made collaboration workflow

*Use a git-based CI workflow to manage documentation changes, contributions, and initiatives.*

Go where the development is. Whether it’s GitHub, GitLab, Bitbucket, or another code hosting service, you can tap into these platforms to develop Docs as Code. Not only does a git-based CI workflow give you collaboration and review tools for free, it also encourages collaboration to happen across teams. As a result, the docs become part of the software development process. And that means many more people feel ready to support the effort to improve the docs.

*Manage teams and permissions by leveraging existing development infrastructure.*

Chances are, your software product already has a well-defined team, permission structure, and contributor community. You can use the same organization or build on it to manage your docs team. These platforms can serve as an administrative and management interface for your docs, whether it’s to monitor activity or grant access to perform certain actions.

== Produce a site from a simple playbook

*Describe what you want to make and Antora takes it from there.*

Antora was built for writers first. Writers want to write, not fiddle with reconfiguring software. That’s where Antora’s playbook comes in. A playbook is a concise way to describe the site you want to produce. This description boils down to a) where to get the content, b) what UI to apply to the pages, and c) where to publish it. That’s all Antora needs to know to do its job. Only when you’re looking for additional customization do you need to dive deeper.

*Offline first.*

A site generated using Antora can be viewed entirely offline. All the references in the site are self-contained (i.e., relative), so you don’t need to run a web server to view it. Just open one of the generated HTML files in your browser and from there you can navigate to all the pages from the UI. Even redirects work offline by default. If a web server is available, you can pass additional configuration to tell Antora to take advantage of its capabilities.

== Bring together content from multiple repositories

*Use a single build to aggregate documentation that spans repository boundaries and branches.*

Most site generators are confined to a single branch of a single repository. Antora, on the other hand, knows how to speak git. It goes out and gathers up all the content the site needs using its built-in git client. It then sorts through the files by separating them into versions of components. This allows you to store the documentation in a way that works best for your organization, whether it means keeping content with code or using separate repositories. Antora can round up all those disparate projects and repositories and create an integrated site.

*Pick and choose content to handcraft your site.*

You won’t always want to include everything in the site. Sometimes, you just want to build a “microsite” that includes a reduced selection of products or versions. Or perhaps you just need to preview the documentation for the product you’re currently working on. The playbook lets you produce multiple variations of a site from the same content sources simply by tuning which sources you draw from.

