= Antora Documentation

[discrete]
=== The Static Site Generator for Tech Writers

This site hosts the tehnical documentation for Antora. 
Antora makes it easy for tech writers to create documentation and publish it to the web.
As a tech writer, you focus on authoring content in xref:asciidoc:asciidoc.adoc[AsciiDoc], Antora's content markup lenguage.
You organize those files into a standard project structure and store them in one or more content (git) repositories. 
Antora picks up your content from there and transforms it into a website. 
That’s all there is to it!

== Manage docs as code

With Antora, you menage *docs as code*.
That means your documentation process benefits from the same practices used to produce successful software.

Some of these practices include:

* Storing content in a version control system.
* Separating content, configuration, and presentation.
* Leveraging automation for compilation, validation, verification, and publishing.
* Reusing shared materials (DRY).

Antora helps you incorporate these practices into your documentation workflow. As a result, your documentation is much easier to manage, maintain, and enhance.

== Where to begin

If you're just beginning your journey with Antora, you'll probably want to know xref:features.adoc[how Antora can help you.]
When you're familiar with this basic concepts, you can try out Antora using the xref:install_and_run_quickstart.adoc[Antora quickstart guide.]

If you're ready to set up a new documentation project, or you want to migrate an existing project to Antora, start by xref:organize_content_files.adoc [organizing your documentation files] into the project structure Antora expects.You'll then need to xref:playbook:index.adoc[create a playbook] to tell Antora where to find the documentation and UI to use for your site.

If you already have a documentation component set up, and you're ready to create your first site, check that you've met Antora's xref:install:supported_platforms.adoc[system requirements],then xref:install:install_antora.adoc[install Antora], and finally xref:run_antora.adoc[generate your site] using the `antora` command.

If you want to jump into writing, learn how to use the Asciidoc syntax to xref:page:index.adoc[make documentation pages.]

If you want to dive deeper into the details of the site generator pipeline, check out xref:how_antora_works.adoc[how Antora works.]

We hope you find making documentation sites with Antora enjoyable and rewarding. Happy writing!