= Align Content by Cell

The alignment operators are applied to a xref:add-cells-and-rows.adoc#cell-specifiers[cell’s specifier] and allow you to horizontally and vertically align a cell’s content.

[#horizontal-opetators]
== Horizontal alignment operators

Content can be horizontally aligned to the left or right side of the cell as well as the center of the cell.

Flush left operator (<)::
The less-than sign (`<`) aligns the content to the left side of the cell. This is the default horizontal alignment.
Flush right operator (>)::
The greater-than sign (`>`) aligns the content to the right side of the cell.
Center operator (^)::
The caret (`^`) centers the content horizontally in the cell.

A horizontal alignment operator is entered after a span or duplication operator (if present) and in front a <<vertical-operators,vertical alignment operator>> (if present).

=== Center content horizontally in a cell

To horizontally center the content in a cell, place the `^` operator in front of the xref:add-cells-and-rows.adoc#cell-specifiers[cell’s separator] (`|`). Don’t insert any spaces between the `|` and the operator.

.Center the content of a cell horizontally
[source#ex-center]
----
include::../examples/example-table.adoc[tag=table-q]
----

The table from <<ex-center, Example 1>> is displayed below.

.Result of <<ex-center>>
====
include::../examples/example-table.adoc[tag=table-q]
====

If the cell specifier includes a span (`<n>+`) or duplication (`<n>*`), place the `^` directly after the span or duplication operator.

.Center content horizontally in spanned columns and duplicated cells
[source#ex-center-horizontal]
----
include::../examples/example-table.adoc[tag=table-1]
----

The table from <<ex-center-horizontal, Example 2>> is displayed below.

.Result of <<ex-center-horizontal>>
====
include::../examples/example-table.adoc[tag=table-1]
====

== Align the content of a cell to the right

To align the content in a cell to its right side, place the `>` operator in front of the xref:add-cells-and-rows.adoc#cell-specifiers[cell’s separator] (`|`), but after a span (`<n>+`) or duplication (`<n>*`) operator (if present). Don’t insert any spaces between the | and the operators.

.Right align the content of a cell
[source#ex-right-align]
----
include::../examples/example-table.adoc[tag=table-2]
----

The table from <<ex-right-align, Example 3>> is displayed below.

.Result from <<ex-right-align>>
====
include::../examples/example-table.adoc[tag=table-2]
====

[#vertical-operators]
== Vertical alignment operators

Content can be vertically aligned to the top or bottom of a cell as well as the center of a cell. Vertical alignment operators always begin with a dot (`.`).

Flush top operator (.<)::
The dot and less-than sign (`.<`) aligns the content to the top of the cell. This is the default vertical alignment.
Flush bottom operator (.>)::
The dot and greater-than sign (`.>`) aligns the content to the bottom of the cell.
Center operator (.^)::
The dot and caret (`.^`) centers the content vertically.

A vertical alignment operator is entered after a <<horizontal-opetators,horizontal alignment operator>> (if present) and in front of a style operator (if present).

=== Align content to the bottom of a cell

To align the content to the bottom of a cell, place the `.>` operator in front of the xref:add-cells-and-rows.adoc#cell-specifiers[cell’s separator] (`|`). Don’t insert any spaces between the `|` and the operator.

.Align content to the bottom of a cell
[source#ex-align-bottom]
----
include::../examples/example-table.adoc[tag=table-3]
----

The table from <<ex-align-bottom, Example 4>> is displayed below.

.Result of <<ex-align-bottom>>
====
include::../examples/example-table.adoc[tag=table-3]
====

If the cell specifier includes a span (`<n>+`) or duplication (`<n>*`), place the `.>` after the span or duplication operator.

.Align content to the bottom of a cell that spans rows
[source#ex-align-content-bottom]
----
include::../examples/example-table.adoc[tag=table-4]
----

The table from <<ex-align-content-bottom, Example 5>> is displayed below.

.Result of <<ex-align-content-bottom>>
====
include::../examples/example-table.adoc[tag=table-4]
====

=== Center content vertically in a cell

To vertically center the content in a cell, place the `.^` operator in front of the xref:add-cells-and-rows.adoc#cell-specifiers[cell’s separator] (`|`). Don’t insert any spaces between the `|` and the operator.

.Center the content of a cell vertically
[source#ex-center-vertical]
----
include::../examples/example-table.adoc[tag=table-5]
----

The table from <<ex-center-vertical, Example 6>> is displayed below.

.Result of <<ex-center-vertical>>
====
include::../examples/example-table.adoc[tag=table-5]
====

== Apply horizontal and vertical alignment operators to the same cell

A cell can have a vertical and <<horizontal-opetators,horizontal alignment operator>> included in its cell specifier. The horizontal operator always precedes the <<vertical-operators,vertical operator>>.

.Align cells horizontally and vertically
[source#ex-align-horizontal-vertical]
----
include::../examples/example-table.adoc[tag=table-6]
----

The table from <<ex-align-horizontal-vertical,Example 6>> is displayed below.

.Result of <<ex-align-horizontal-vertical>>
====
include::../examples/example-table.adoc[tag=table-6]
====