= Build a Basic Table

A table is a delimited block that can have optional customizations, such as an ID and a title, as well as table-specific attributes, options, and roles. However, at its most basic, a table only needs columns and rows.

On this page, you’ll learn:
* [x]  How to set up an AsciiDoc table block and its attribute list.
* [x] How to add columns to a table using `cols` attribute.
* [x] How to use cells to a table and arrange them into rows.
* [x] How to designate a row as a table's header row.

== Create a table with two columns and three rows

In <<ex-set-up-table, Example 1>>, we'll assign the `cols` attribute a list of column specifiers.
A column specifier represents a column.

.Example 1: Set up a table with two columns
[source#ex-set-up-table]

----
[cols="1,1"] # <.> <.>
|=== # <.>
----

<.> On a new line, create an attribute list. Set the `cols` attribute, followed by an equals sign (`=`).
<.>  Assign a list of comma-separated column specifiers enclosed in double quotation marks (`"`) to `cols`. Each column specifier represents a column.
<.> On the line directly after the attribute list, enter the opening table delimiter. A table delimiter is one vertical bar followed by three equals signs (`|===`). This delimiter starts the table block.

The table in <<ex-set-up-table, Example 1>> will contain two `columns` because there are two comma-separated entries in the list assigned to `cols`. Each entry in the list is called a column specifier. A *column specifier* represents a column and the width, alignment, and style properties assigned to that column. When each column specifier is the same number, in this case the integer `1`, all of the columns’ widths will be identical. Each column in <<ex-set-up-table, Example 1>> will be the same width regardless of how much content they contain.

Next, let’s add three rows to the table. Each row has the same number of cells. Since the table in <<ex-three-rows, Example 2>> has two columns, each row will contain two cells. A cell starts with a vertical bar (`|`).

.Example 2: Add three rows to the table
[source#ex-three-rows]

----
[cols="1,1"]
|===
|Cell in column 1, row 1 # <.>
|Cell in column 2, row 1 # <.>
# <.>
|Cell in column 1, row 2 
|Cell in column 2, row 2

|Cell in column 1, row 3
|Cell in column 2, row 3 # <.>
|=== # <.>
----

<.>  To create a new cell, press kbd:[Shift+|]. After the vertical bar (`|`), enter the content you want displayed in that cell.
<.>  On a new line, start another cell with a `|`. Each consecutive cell is placed in a separate, consecutive column in a row.
<.>  Rows are separated by one or more empty lines.
<.>  When you finish adding cells to your table, press kbd:[Enter] to go to a new line.
<.>  Enter the closing delimiter (`|===`) to end the table block.

TIP: The suggestion to start each cell on its own line and to separate rows by empty lines is merely a stylistic choice. You can enter more than one cell or all of the cells in the row on the same line since the processor creates a new cell each time it encounters a vertical bar (`|`).

The table from <<ex-three-rows, Example 2>> is displayed below. It contains two columns and three rows of text positioned and styled using default alignment, border, and width attribute values.

====
include::../examples/example-table.adoc[tag=table-b]
====