= Highlights
:url-asciidoc: https://docs.asciidoctor.org/asciidoc/latest
:url-highlight: {url-asciidoc}/text/highlight/
:url-formatting: {url-asciidoc}/text/#formatting-marks-and-pairs
:url-constrained: {url-asciidoc}/text/troubleshoot-unconstrained-formatting/

On this page, you'll learn:

* [x] How to highlight text with AsciiDoc.
* [x] Where to modify your site’s highlighting styles.

== Highlight syntax
To highlight (or mark) a word or phrase, place a hash (`#`) at the beginning and end of the text you wish to format (constrained formatting). To highlight one or more characters bounded by other characters, place two hashes (`##`) before and after the characters (unconstrained formatting).

.Highlight inline formatting
[#ex-highlight]
----
Let's #highlight this phrase# and the i and s in th##is##.
----

The result of <<ex-highlight>> is displayed bellow.
====
Let's #highlight this phrase# and the i and the s in th##is##.
====

== Sites styles
How highlighted text appears on your site depends on the CSS styles applied to the `<mark>` HTML tag. You can learn more about customizing how highlighted text appears in your site in the UI documentation.

.AsciiDoc and AsciiDoctor resources

* {url-highlight}[Monospace text formatting]
* {url-formatting}[Formatting marks and pairs]
* {url-constrained}[Constrained versus unconstrained]