= Italic
:url-asciidoc: https://docs.asciidoctor.org/asciidoc/latest
:url-italic: {url-asciidoc}/text/italic/
:url-formatting: {url-asciidoc}/text/#formatting-marks-and-pairs
:url-constrained: {url-asciidoc}/text/troubleshoot-unconstrained-formatting/

On this page, you'll learn:

* [x]  How to italicize text in AsciiDoc.
* [x]  Where to modify your site’s italic text styling.

Text is often italicized in order to stress a word or phrase, quote a speaker, or introduce a term. Italic type slants slightly to the right, and depending on the font, may have cursive swashes and flourishes.

== Italic syntax
A word or phrase is marked as italic when it is enclosed in a single set of underscores (`_word_`) (constrained formatting). Bounded characters are marked as italic when they’re enclosed in a set of double underscores (`char__act__ers`) (unconstrained formatting).

Bounded characters are characters that are:

* directly preceded by a non-whitespace character, or
* directly followed by a non-whitespace character.

You don’t need to use double underscores when an entire word or phrase marked as italic is directly followed by a common punctuation mark, such as `;`, `"`, and `!`.

.Italic inline formatting
[#ex-italic]
----
An italic _word_, and an italic _phrase of text_.

Italic c__hara__cter__s__ within a word.
----
The result of <<ex-italic>> id displayed bellow.

====
An italic word, and an italic phrase of text.

Italic characters within a word.
====

== Mixing italic with other formatting
You can add multiple emphasis styles to italic text as long as the syntax is placed in the correct order.

.Order of inline formatting syntax
[#ex-format]
----
`*_monospace bold italic phrase_*` & ``**__char__**``acter``**__s__**``
----

xref:monospace.adoc[Monospace syntax] (```) must be the outermost formatting set. xref:bold.adoc[Bold syntax] (`*`) must be outside the italics formatting set. Italic syntax is always the innermost formatting set.

The result of <<ex-format>> is displayed bellow.

====
monospace bold italic phrase & characters
====

== Sites styles
How italic text appears on your site depends on the fonts loaded by your UI and any CSS styles applied to the `<em>` HTML tag. You can learn more about customizing how italic text appears in your site in the UI documentation.

.AsciiDoc and AsciiDoctor resources

* {url-italic}[Italic text formatting]
* {url-formatting}[Formatting marks and pairs]
* {url-constrained}[Constrained versus unconstrained]